# Reference: https://www.poornerd.com/2020/08/31/deploy-nextjs-github-actions.html
name: Build Website

on:
  push:
    branches: [ main, documentation ]

defaults:
      run:
        working-directory: website

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2.1.0
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npx next build
    - run: npx next export
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: /home/runner/work/harvest/harvest/website/out
     
